### ISSUE TITLE
directories are not right

### ISSUE THREAD

**Issue by liu-xiao-guo** [ubuntudesign/snapcraft.io#174] opened 2016-08-09 02:59 UTC
on the page page, the following directories seem not right:

~/snap/<name>/current/      ← $SNAP_USER_DATA that can be rolled back
~/snap/<name>s/common/       ← $SNAP_USER_COMMON unversioned user-specific data

There is a typo "s" in the above

If I run my hello-world example, and the directories are:

liuxg@liuxg:~$ hello-xiaoguo.env | grep SNAP
SNAP_USER_COMMON=/home/liuxg/snap/hello-xiaoguo/common
SNAP_LIBRARY_PATH=/var/lib/snapd/lib/gl:
SNAP_COMMON=/var/snap/hello-xiaoguo/common
SNAP_USER_DATA=/home/liuxg/snap/hello-xiaoguo/x1
SNAP_DATA=/var/snap/hello-xiaoguo/x1
SNAP_REVISION=x1
SNAP_NAME=hello-xiaoguo
SNAP_ARCH=amd64
SNAP_VERSION=1.0
SNAP=/snap/hello-xiaoguo/x1

so, the directory is something like:

/home/liuxg/snap/hello-xiaoguo/x1 ==> ~/<user_name>/snap/app_name/current
/home/liuxg/snap/hello-xiaoguo/common ==> ~/<user_name>/snap/app_name/common

**Comment by magdalena-mirowicz** [comment] 2016-08-10 16:16
Duplicate of #174

**Closed by magdalena-mirowicz** 2016-08-10 16:16 UTC
Labels: Status: Duplicate
